### ISSUE TITLE
docker中运行example中wide_deep.py报错

### ISSUE THREAD

**Issue by ZhangYaoFu** [Qihoo360/tensornet#8]
报错如下，原因是dockerfile中安装的python版本是3.6，而Datetime.fromisoformat 是python3.7才支持的。

```
Traceback (most recent call last):
  File "wide_deep.py", line 231, in <module>
    main()
  File "wide_deep.py", line 196, in main
    delta_day = trained_delta_days(dt)
  File "wide_deep.py", line 165, in trained_delta_days
    last_train_dt = datetime.fromisoformat(last_train_dt)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
I1008 07:02:47.883709   883 external/brpc/src/brpc/server.cpp:1100] Server[tensornet::PsServiceImpl] is going to quit
```

**Comment by zhangys-lucky** [comment]
推荐自行编译一个，我们这里人比较少，没有太多精力维护docker，望见谅。如果需要docker环境的可以按照git里的dockerfile自行创建，上面这个环境问题麻烦自己调一下
